apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-deployment
  labels:
    app: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
      - name: log-app
        image: ugwuanyi/log-app:latest
        resources:
            requests:
              memory: "64Mi" 
              cpu: "250m" # 0.25 CPU
            limits:
              memory: "128Mi" 
              cpu: "500m" # 0.5 CPU