apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.modules:

    filebeat.config:
      prospectors:
        path: ${path.config}/prospectors.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false

    processors:
    - add_cloud_metadata:

    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/app/*.log

    output.logstash:
      hosts: ['logstash-service:5044']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-deployment
  labels:
    app: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
      - name: log-app
        image: ugwuanyi/log-app:latest
        resources:
            requests:
              memory: "64Mi" 
              cpu: "250m" # 0.25 CPU
            limits:
              memory: "128Mi" 
              cpu: "500m" # 0.5 CPU
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-logging
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
            cpu: 150m
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: filebeat-config-vol
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml

      volumes:
      - name: filebeat-config-vol
        configMap:
          defaultMode: 0600
          name: filebeat-config
