# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-configmap
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "emeka-cluster"
    network.host: 0.0.0.0
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  elasticsearch
  namespace: default
  labels:
    app:  elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  elasticsearch
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  elasticsearch
        image:  elasticsearch:7.16.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "1"
            memory: 2Gi
        
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: discovery.type
          value: single-node
            
        ports:
        - containerPort:  9200
          name:  elasticsearch1
        - containerPort:  9300
          name:  elasticsearch2

        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /data
        - name: elastic-configmap-volume
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml

      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
      - name: elastic-configmap-volume
        configMap:
          name: elastic-configmap
          items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - name: elasticsearch
    protocol: TCP
    port: 9200
    targetPort: 9200
---
