# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kibana
  namespace: default
  labels:
    app:  kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  kibana
    spec:
      containers:
      - name:  kibana
        image:  kibana:7.16.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.default.svc.cluster.local:9200 #TODO
        ports:
        - containerPort:  5601
          name:  kibana
        
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
  - name: kibana
    protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30001
---
