apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-configmap
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    version: v6.2.4
spec:
  serviceName: elasticsearch-logging
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v6.2.4
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v6.2.4
    spec:
      containers:
      - image: ugwuanyi/elastic:latest # docker.elastic.co/elasticsearch/elasticsearch:8.3.2
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging
          mountPath: /data
        # - name: elastic-configmap-volume
        #   mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
        #   subPath: elasticsearch.yml
        env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: discovery.type
            value: single-node
          - name: ELASTIC_PASSWORD
            value: changeme

      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
      - name: elastic-configmap-volume
        configMap:
          name: elastic-configmap
          
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/name: "Elasticsearch"
spec:
  type: ClusterIP
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    # name: port1
  # - port: 9300
  #   protocol: TCP
  #   targetPort: 9300
  #   name: port2
  selector:
    k8s-app: elasticsearch-logging
